version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 3000
      runas: root
  AfterInstall:
    - location: pull.sh
      timeout: 9000
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 3000
      runas: root