AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample: Create
  an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security
  group for the instance to give you SSH access. **WARNING** This template
  creates an Amazon EC2 instance. You will be billed for the AWS resources used
  if you create a stack from this template.
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: orange
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  IAM:
    Description: Name of the IAM role to be attached in this instance
    Default: ssp-custom-all
    Type: AWS::IAM::InstanceProfile
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.xlarge
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings:
  AWSInstanceType2Arch:
    
    t2.xlarge:
      Arch: HVM64
    t2.large:
      Arch: HVM64
    
  AWSInstanceType2NATArch:
    t2.xlarge:
      Arch: NATHVM64
    t2.large:
      Arch: NATHVM64
    
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-04505e74c0741db8d
      HVMG2: NOT_SUPPORTED
    us-west-2:
      HVM64: ami-0892d3c7ee96c0bf7
      HVMG2: NOT_SUPPORTED
    us-west-1:
      HVM64: ami-01f87c43e618bf8f0
      HVMG2: NOT_SUPPORTED
    us-east-2:
      HVM64: ami-0fb653ca2d3203ac1
      HVMG2: NOT_SUPPORTED
    
 # AWSRegionArch2AMI:
 #   us-east-1: ami-04505e74c0741db8d
 #   us-east-2: ami-0fb653ca2d3203ac1
    
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
        - !Ref InstanceHTTPSecurityGroup
        - !Ref InstanceHTTPsSecurityGroup
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref IAM
      MapPublicIpOnLaunch: false
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt update
            sudo apt upgrade -y
            sudo su
            my_repo=$(aws ssm get-parameter --name "git_url_qc" --region us-east-2 --query 'Parameter.Value' --output text)
            git clone $gym

      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
  InstanceHTTPSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref SSHLocation
  InstanceHTTPsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref SSHLocation
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicIp
  PrivateIP:
    Description: Private IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PrivateIp
