AWSTemplateFormatVersion: 2010-09-09

Resources:  
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      
      ImageId: ami-0fb653ca2d3203ac1
      InstanceType: t2.large
      KeyName: orange
      IamInstanceProfile: ssp-custom-all
      SecurityGroupIds: sg-099b9caf0073e0a4e
      AssociatePublicIpAddress: false
      DeleteOnTermination: true
      SubnetId: subnet-92a95fef
      UserData:
        Fn::Base64: |
            #!/bin/bash
            sudo apt update
            sudo apt upgrade -y
            my_repo=$(aws ssm get-parameter --name "git_url_qc" --region us-east-2 --query 'Parameter.Value' --output text)
            git clone $my_repo
          
