AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: orange
    Type: String
  IAM:
    Description: Name of the IAM role to be attached in this instance
    Default: ssp-custom-all
    Type: String
  SecurityGroup:
    Description: Id of the Security Group
    Default: sg-099b9caf0073e0a4e
    Type: String
  SubnetId:
    Description: The Subnet Id to be used
    Default: subnet-92a95fef
    Type: String
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.xlarge
      - t2.large
  ImageID:
    Description: Ami Id of the instance
    Default: ami-0fb653ca2d3203ac1
    Type: String

Resources:  
  DemoInstance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      
      ImageId: 
        Ref: ImageID
      InstanceType: 
        Ref: InstanceType
      KeyName: 
        Ref: KeyName
      IamInstanceProfile: 
        Ref: IAM
      SecurityGroupIds: 
        Ref: SecurityGroup
      AssociatePublicIpAddress: false
      DeleteOnTermination: true
      SubnetId: 
        Ref: SubnetId
      UserData:
        Fn::Base64: |
            #!/bin/bash
            sudo apt update
            sudo apt upgrade -y
            my_repo=$(aws ssm get-parameter --name "git_url_qc" --region us-east-2 --query 'Parameter.Value' --output text)
            git clone $my_repo
          
